-- CREATE TABLE IF NOT EXISTS scores (
--     -- id SERIAL PRIMARY KEY NOT NULL,
--     player VARCHAR(127),
--     score INTEGER
  
-- );
CREATE TABLE IF NOT EXISTS words (
    -- id SERIAL PRIMARY KEY NOT NULL,
    word VARCHAR(125) NOT NULL,
    id INTEGER PRIMARY KEY NOT NULL
);